config/routes.rb
Rails.application.routes.draw do
  # get 'messages/reply'

  resources :events do
    get '/sendsms', to: 'messages#send'
  end 

    # resource :messages do
    #   collection do
    #     post 'reply'
    #     get 'send_sms'
    #   end
    # end

  root to: "welcome#home"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :check

  


  resources :checks
  resources :users

  get "/dashboard", to: "welcome#dashboard"

 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord

end

app/models/event.rb
class Event < ApplicationRecord

  @@pending = []
  
  def remind?
    if self.start_time.strftime("%Y %m %d %H") == Time.now.strftime("%Y %m %d %H")
      if self.start_time.min - Time.now.min <= 30
        return true
        true
      end
    end
    return false
  end

  def self.send_sms(event, val = client)
    if remind?
      val.account.messages.create(
        from: "+13474175794",
        to: '+17182005194',
        body: "Reminder, you have an event: #{event.description} in 30 min!"
      )
    end
  end

  belongs_to :user

end
 

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:linkedin]
  has_many :events       

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/models/wallpaper.rb
class Wallpaper < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController

  def index
    @events = Event.all.select{|event| event.start_time.strftime("%d") == Time.now.strftime("%d")}
    @check = Check.new
  end

 def create
   @num_arr = params[:check][:id][1..-1]
   @num_arr.each do |event_id|
     binding.pry
     event = Event.find_by(id: event_id.to_i)
     event.status = true
     event.save
   end
 end


end

app/controllers/dashboard_controller.rb
class UsersController < ApplicationController
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
<<<<<<< HEAD
  end 
=======
    @user = current_user
  end
>>>>>>> master

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
<<<<<<< HEAD
    @event = Event.new(event_params)
=======

    @event = Event.new(event_params)
    @event.user_id = current_user.id
>>>>>>> master
    respond_to do |format|
      if @event.save
        @@pending << @event
        binding.pry
        # format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.html { redirect_to event_sendsms_path(@event), notice: 'Event was successfully created.' }

        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event

      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:description, :start_time)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
 skip_before_filter :verify_authenticity_token, :authenticate_user!
 before_action :boot_twilio

  def reply
    message_body = params["Body"]
    from_number = params["From"]
    sms = @client.messages.create(
      from: "+13474175794",
      to: from_number,
      body: "Hello there, thanks for texting me. Your number is #{from_number}."
    ) 
  end

<<<<<<< HEAD
  def send
    @event = Event.find_by(id: params[:event_id])
    Event.send_sms(@event, @client)
    # @client.account.messages.create(
    #   from: "+13474175794",
    #   to: '+17182005194',
    #   body: "Reminder, you have an event: #{@event.description} in 30 min!"
    # ) 
=======
  def send_sms
    @client.account.messages.create(
      from: "+13474175794",
      to: '+17182005194',
      body: "hay"
    ) 
>>>>>>> master
     redirect_to root_path, alert: 'Event was successfully created.'
  end
 
  private
 
  def boot_twilio
    account_sid = 'ACb81a290e1ff16bee1b0f52a72b0991ef'
    auth_token = '7f54bf3a2172c2273c897db66e9cb2e5'
    @client = Twilio::REST::Client.new account_sid, auth_token
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def linkedin
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home

    @user = current_user
    @events = Event.all
    @quote = Quote.all.sample
    @wallpaper = Wallpaper.all.sample
    @event = Event.new
  end

  def dashboard
    events = current_user.events.where('status = ?', true)
    @events = events.where('start_time <= ?', Time.now)
    if @events.all.size != 0
      redirect_to events_path
   end
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/check/index.html.erb
 CHECK YOUR SUCCESSFULLY COMPLETED EVENTS AND CLICK ENTER

<%= form_for @check do |f| %>
<%= f.collection_check_boxes :id, @events, :id, :description %>
<%= f.submit %>
<% end %>

app/views/checks/index.html.erb
 CHECK YOUR SUCCESSFULLY COMPLETED EVENTS AND CLICK ENTER

<%= form_for @check do |f| %>
<%= f.collection_check_boxes :id, @events, :id, :description %>
<%= f.submit %>
<% end %>

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %> |
<%= link_to "Home", root_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="center">
  <h1>Events</h1>
</div><br>
<%= button_to 'New Event', new_event_path, method: "get" %><br>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><h2><%= event.description %></h2></td>
        <td><h2><%= event.start_time %></h2></td>
        <td><h2><%= link_to 'Show', event %></h2></td>
        <td><h2><%= link_to 'Edit', edit_event_path(event) %></h2></td>
        <td><h2><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></h2></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %> |
<%= link_to "Home", root_path %><br><br>
<%= button_to "delete", @event, :method => :delete %> 

app/views/layouts/_header.html.erb
<nav class="nav">

<% if user_signed_in? %>
  <ul class="topnav" id="myTopnav">
   <li><%= link_to "Home", root_path ,{ :'data-no-turbolink' =>  "true" }%></li>
   <li> <%= link_to "My Dashboard", dashboard_path %></li>
   <li><%= link_to "Events List", events_path %>></li>
   <li><%= link_to "Sign Out", destroy_user_session_path, :method => "delete" %></li>
   <li class="icon">
     <a href="javascript:void(0);" style="font-size:15px;" onclick="myFunction()">☰</a>
   </li>
  </ul>


  <script>
  function myFunction() {
     var x = document.getElementById("myTopnav");
     if (x.className === "topnav") {
         x.className += " responsive";
     } else {
         x.className = "topnav";
     }
  }
  </script>
  <% elsif !current_page?(new_user_session_path) && !current_page?(new_user_registration_path)   %>

  <ul class="topnav" id="myTopnav">
   <li><%= link_to "Home", root_path ,{ :'data-no-turbolink' =>  "true" }%></li>
   <li><a href="#news">Dashboard</a></li>
   <li><a href="#contact">Contact</a></li>
   <li><a href="#about">About</a></li>
   <li class="icon">
     <a href="javascript:void(0);" style="font-size:15px;" onclick="myFunction()">☰</a>
   </li>
  </ul>


  <script>
  function myFunction() {
     var x = document.getElementById("myTopnav");
     if (x.className === "topnav") {
         x.className += " responsive";
     } else {
         x.className = "topnav";
     }
  }
    <% end %>




</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnTrack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <style type="text/css">
    body {
      background-size: cover;
      background-repeat: no-repeat;
      background-attachment: fixed;
    }
  </style>

  <body>
    <img src="
https://www.pplelectric.com/~/media/pplelectric/my%20account/images/ontrack/ontrack-logo.png " alt="Mountain View" style="">
    <%= render 'layouts/header' %>



</style>
</head>
<body>




    <%= yield %>





  </body>
</html>

app/views/messages/reply.html.erb
<h1>Messages#reply</h1>
<p>Find me in app/views/messages/reply.html.erb</p>

app/views/messages/send_sms.html.erb
<

app/views/user/show.html.erb
hello

app/views/welcome/dashboard.html.erb
<br>
<div class="center">
  <% points = (100 - (current_user.events.all.count - @events.count)*100 /current_user.events.all.count)  %>
  <h1>You have <%= points  %>% successful events!</h1>
  <h2>
    <% if points < 33 %>
    <%= "You need to try harder." %>
    <% elsif  points < 66 %>
    <%= "You are not consistent enough, but good work" %>
    <% else %>
    <%= "Great Work you are on your way to success!" %>
    <% end %>
  </h2>

</div>

app/views/welcome/home.html.erb
<div class="center">
<h2>"<%= @quote.description %>"</h2>
<h3>-<i><%= @quote.author %></i></h3>
</div>

<main style="background-image: linear-gradient(to bottom,rgba(255,255,255, 0.2), rgba(255,255,255, 0.2)), url(<%= Wallpaper.all.sample.link %>)">
  <%= month_calendar events: @events do |date, events| %>
  <strong><%= date.day %></strong> <br>
  <div class="calendar-cell" style="visibility:hidden">
  <%= @event.start_time = date %>
  <%= form_for(@event) do |f| %>
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

<<<<<<< HEAD
<% if date.to_s == Time.now.strftime("%Y-%m-%d") && Time.now.strftime("%H").to_i < 18  %>
  <% if events.length < 2 %>
    <%= link_to "Create Your Tasks", new_event_path%>
  <% end %>
<% end%>

<% if Time.now.strftime("%H").to_i > 18 && date.to_s == Time.now.strftime("%Y-%m-%d") && events.length > 0%>
 <%= link_to "Go over daily tasks", check_index_path %>
<% end %>
=======
    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description%>
    </div>

>>>>>>> master

    <div class="field">
      <%= f.datetime_select :start_time %>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

  <% if date.to_s == Time.now.strftime("%Y-%m-%d") && Time.now.strftime("%H").to_i < 18 && Time.now.strftime("%H").to_i > 9  %>
    <% if events.length < 2 %>
      <%= link_to "Create Your Tasks", new_event_path%>
    <% end %>
  <% end%>

  <% if Time.now.strftime("%H").to_i > 5 && date.to_s == Time.now.strftime("%Y-%m-%d")%>
   <%= link_to "Mark tasks", checks_path %>
  <% end %>

    <% events.each do |event| %>
      <div class="field">
        <i><%= event.start_time.strftime("%I:%M %p") %></i>
        <%= link_to "#{event.description}", event_path(event), { :class => 'field'} %>
      </div>
    <% end %>
  <% end %>
</main>